"""add column users.phone_number

Revision ID: 8b31a48edd35
Revises: fa6a3d2d52e3
Create Date: 2024-05-16 08:42:09.223855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b31a48edd35'
down_revision: Union[str, None] = 'fa6a3d2d52e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
